### ISSUE TITLE
Support python2.7

### ISSUE THREAD

**Issue by shalei6698** [nvim-neotest/neotest-python#11]
![image](https://user-images.githubusercontent.com/5708724/178399985-992e1daa-1e3a-49d2-acf9-0dfeab076543.png)

**Comment by rcarriga** [comment]
I'm sorry but Python 2.7 does not support type annotations which I see as an essential part of the code base, and that's just the beginning, there would likely be more incompatibilities that would have to be fixed and maintained. This is just not something I have the time or interest in to do. 

If someone wanted, they could fork this repo and make the changes. The underlying adapter logic should be the same.
