### ISSUE TITLE
Deselected tests are considered failed

### ISSUE THREAD

**Issue by cblessing24** [nvim-neotest/neotest-python#13]
Consider the following test:

```python
@pytest.mark.slow
def test_foo():
    assert True
```

We can deselect this test using the following command:

```bash
pytest -m 'not slow' tests
```

This will run all tests in `tests` that are not marked `slow`. We can do the same using neotest but unfortunately the deselected tests will be considered failed which is incorrect because they did not run in the first place. I think it would be better to consider them skipped or their status unknown.

**Comment by rcarriga** [comment]
This should now be working as expected :smile:

**Comment by cblessing24** [comment]
Yup, works perfectly now. Thanks a lot! :)
