### ISSUE TITLE
Mock.patch not working

### ISSUE THREAD

**Issue by lucasscvvieira** [nvim-neotest/neotest-python#15]
when i run the pytest in the neovim, the mock patch can't find the module `src.server`, but when i run outside the nvim it works.

![image](https://user-images.githubusercontent.com/27821011/185998071-1d3df142-94dc-4834-ab86-a7a33be0cb5b.png)

**Comment by rcarriga** [comment]
I have absolutely no idea what your project looks like or how to reproduce this. Please provide a repo so that I can reproduce

**Comment by lucasscvvieira** [comment]
I think its a wrong configuration of pyenv or venv :thinking: I recreated my environment and now it works
