### ISSUE TITLE
Custom envs not working

### ISSUE THREAD

**Issue by lukerops** [nvim-neotest/neotest-python#16]
I have helper [code](https://github.com/lucasscvvieira/dotfiles/blob/main/.config/nvim/lua/utils/envs.lua) that loads my .env file and passes it to `neotest.run.run` ([here](https://github.com/lucasscvvieira/dotfiles/blob/872d1c837cf5248bad9b5f30b849f7218378f828/.config/nvim/lua/config/neotest.lua#L16)), but the envs are not passed to pytest.

---

test.py
```python
import os


def test_1():
    print(os.environ.get('APICONFIG_URL', 'Env not found!'))
    print(list(os.environ.keys()))
    raise Exception()
```

----

.env
```
APICONFIG_URL='http://localhost/'
```

---

![image](https://user-images.githubusercontent.com/27821011/186243884-c56758fa-287e-4312-81d1-84d7f6856aeb.png)

**Comment by rcarriga** [comment]
I tested by changing your code to run when running the test, instead of loading beforehand and it works just fine. Are you sure that the env is correctly loaded?
```lua
  local get_env = function()
    local env = {}
    for _, file in ipairs({ ".env" }) do
      if vim.fn.empty(vim.fn.glob(file)) ~= 0 then
        break
      end

      for _, line in ipairs(vim.fn.readfile(file)) do
        for name, value in string.gmatch(line, "(.+)=['\"]?(.*)['\"]?") do
          local str_end = string.sub(value, -1, -1)
          if str_end == "'" or str_end == '"' then
            value = string.sub(value, 1, -2)
          end

          env[name] = value
        end
      end
    end
    return env
  end
  neotest.run.run({ vim.fn.expand("%"), env = get_env() })
```

**Comment by rcarriga** [comment]
Closing as I can't reproduce and no response has been received
