### ISSUE TITLE
No tests found by neotest-python

### ISSUE THREAD

**Issue by NostraDavid** [nvim-neotest/neotest-python#17]
Had trouble getting this adapter to find my tests and got the "no tests found" notification.

I checked the log, as mentioned in [this issue on neotest itself](https://github.com/nvim-neotest/neotest/issues/59), but found nothing wrong (other than there was no mention that files were found, which started to ring a bell).

I had this code in my config, because part of it was part of the example config in the README.md:

```lua
is_test_file = function(file_path)
  return vim.startswith(file_path, "test_")
end,
```

Turns out this doesn't work. Nor did this:

```lua
is_test_file = function(file_path)
  return file_path:find("^test_") ~= nil
end,
```

Solution:

Don't use `is_test_file`, by either removing the `is_test_file` or commenting it out! The default behavior works just fine.

**Comment by NostraDavid** [comment]
So yes, my problem has already been solved.

However, to ensure others don't need to suffer the same problem, I figure I'd post it here :)

**Comment by rcarriga** [comment]
The default version already does exactly what you want and the README states the configuration values are optional. I don't see any need to add an example that people will unfortunately probably blindly copy and paste with no need, hence why the given one is not valid lua.
