### ISSUE TITLE
Run fails due to 'Config missing "rootpath" attribute'

### ISSUE THREAD

**Issue by dpopchev** [nvim-neotest/neotest-python#21]
- tested on `neovim-0.7.2` and `neovim-0.8.2`
-  with respectively `pytho-3.7` and `python-3.8` 
-  set via `python = vim.g.python3_host_prog`, but absolute path doesn't make a difference
- with `pytest` runner

even for as simple file as
```python3
import pytest

def test_a():
  assert False
```
when cursor is on `test_a` run fails when `:lua require("neotest").run.run()`; NOTE -- when passing `--collect-only` via `args` the window corectly reports found tests.

During the testing, there is a running `jedi_language_server` recognizing project. 

![image](https://user-images.githubusercontent.com/25241182/196413628-f9bf4be1-5385-4d47-bb4e-74265556800b.png)

**Comment by rcarriga** [comment]
I'm guessing you're using a pretty old version of pytest. I've switched to using a different property of the config that should work but I'm not sure if there will other issues.

**Comment by dpopchev** [comment]
I should have figure this earlier -- due to working in restricted environment `pytest-4.6.9`
Switched to venv with `pytest-7.1.3` and all is fine.
