### ISSUE TITLE
Results in parent TestClass affectes reports on nested ones

### ISSUE THREAD

**Issue by dpopchev** [nvim-neotest/neotest-python#26]
Following behavior is using `require('neotest').run.run()`.

While cursor `TestFalseNegative` we get false positive on `TestGroup`:

![image](https://user-images.githubusercontent.com/25241182/198866208-a4d6df2d-1821-4720-be43-5d290f9a0a91.png)

Opening the summayr window on `TestGroup` reviews it failed:
![image](https://user-images.githubusercontent.com/25241182/198868071-e1dc6607-5ae9-4e20-9814-73e483d86e83.png)

Rerunning `TestGroup`, i.e. shows expected. behavior.

Similar effect when making outer fail, but intter pass:
![image](https://user-images.githubusercontent.com/25241182/198868252-231ae36f-ee5d-43cb-8505-8ec9f032dc17.png)

Using `nvim-0.8.0` and `pytest-7.2.0`

EDIT:
Missing any test in parent classes results in fail of nested one.
![image](https://user-images.githubusercontent.com/25241182/198868371-e8585890-0243-47cf-8200-f8aba15501f9.png)

**Comment by rcarriga** [comment]
Thanks for the report! Should be working as expected now :smile:

**Comment by dpopchev** [comment]
Can confirm, thanks!
