### ISSUE TITLE
Running all tests under submobule in test summary panel

### ISSUE THREAD

**Issue by Willem-J-an** [nvim-neotest/neotest-python#45]
I raised this for [neotest](https://github.com/nvim-neotest/neotest/issues/196) but I found the issue originates in this repo.

I provide my arguments to neotest-python like so:
``` py
require("neotest-python")({
  args = {"-p", "*_test.py"}
})
```
These arguments are passed through all the way to the UnittestNeotestAdapter, which happily ignores them.
``` py
# These will be the args up to that point:
args = Namespace(
  runner='unittest',
   results_file='/tmp/nvim.user/yzlLad/0',
   stream_file='/tmp/nvim.user/yzlLad/1',
   args=['-p', '*_test.py', '/home/user/code/mymodule']
 )
```
Processed by the [adapter](https://github.com/nvim-neotest/neotest-python/blob/a76fb6760fc2f653c2088f79152338cc99380cf1/neotest_python/unittest.py#L96)
``` py
# We only get a single case ID as the argument
argv = sys.argv[0:1] + self.id_to_unittest_args(args[-1])
```

This prevents my test file pattern from reaching the TestProgram, where an incorrect pattern is the default: test*.py

And so it was, that not a single test was tested :D
Ran 0 tests in 0.000s

**Comment by rcarriga** [comment]
Thanks for figuring out the issue :smile: I've adjusted the argument parsing to correctly pass user args. Please try with the latest commit

**Comment by Willem-J-an** [comment]
Hi,
Unfortunately it is not working yet for me. 

Prepended the command now becomes this:
``` py
['neotest-python', '-p', '*_test.py', 'discover', '-s', '/home/user/code/module']
```
This is invalid because the pattern must come after discover.
If the args are appended, it does work for me.
``` py
argv = ["neotest-python"] +  self.id_to_unittest_args(args[-1]) + args[:-1]
```

**Comment by rcarriga** [comment]
Ah yep sorry about that, please try latest!

**Comment by Willem-J-an** [comment]
It works now for a directory with multiple tests, but not when running a single test.
neotest-python: error: unrecognized arguments: -p *_test.py
I guess the code path with multiple tests uses discover, which accepts this parameter, but the code path for a single test does not use discover, and does not accept this parameter.

**Comment by rcarriga** [comment]
OK it'll now pass the args in the correct order :sweat_smile:

**Comment by Willem-J-an** [comment]
It doesn't seem quite there yet for me unfortunately. From the summary panel I can:
- Run the _test.py
- Run the -> tests <- /* folder
- Run the -> top <- /tests/*

What no longer works is:
- Running the TestClass
- Running a testmethod

From a testfile I can sucesfully expand and run all, I suppose this runs the entire file, which also works from the summary panel. I can not run a singular test with neotest.run.run().

The reason it does not work seems to be my discover arguments are passed to a non discover command when running a single testcase.
usage: neotest-python [-h] [-v] [-q] [--locals] [-f] [-c] [-b] [-k TESTNAMEPATTERNS] [tests ...]
neotest-python: error: unrecognized arguments: -p

**Comment by rcarriga** [comment]
neotest-python doesn't parse the args you pass, you have to be sure to pass the correct arguments. The `args` option can be a function that receives two arguments: `runner` ("unittest" or "pytest") and `position` which is a [`neotest.Position`](https://github.com/nvim-neotest/neotest/blob/0d17889ce740c83c18577487498a1a8fea144b0b/lua/neotest/types/init.lua#L1) so you can do something like this:
```lua
require("neotest-python")({
  args = function (_, position)
    if position.type == "test" or position.type == "namespace" then
      return {}
    end
    return {"-p", "*_test.py"}
  end
})
```

**Comment by Willem-J-an** [comment]
Ah great, that makes sense now! I would recommend to include this in the docs somewhere? Could be helpful for the next person! :smile:
