### ISSUE TITLE
nvim_buf_get_extmark_by_id trows an 'expected lua number' error

### ISSUE THREAD

**Issue by dpopchev** [nvim-neotest/neotest-python#46]
I was using `neotest-python` and all of the sudden the following error, any time I enter/interact in `insert` mode.

I am not sure how to debug/reproduce or provide more feedback; any guidance is highlight appreciated.

I am aware that the issue might be in `neotest` itself, but didn't find similar issue there; decided to start from here.

PS: restart fixes it; happened on several occasions (rarely), but as it is out of the blue, cannot give guidance to reproduce.

![image](https://user-images.githubusercontent.com/25241182/219855271-deff9ed0-d0a7-480b-b4bc-5b0f4aa6b8aa.png)

**Comment by rcarriga** [comment]
Yeah this definitely a neotest issue, not neotest-python. Unfortunately I can't do much without being able to reproduce, that function expects 3 different number arguments and the error doesn't specify which one is invalid. Please open a bug report with the template filled out
