### ISSUE TITLE
How to run all tests?

### ISSUE THREAD

**Issue by fredrikaverpil** [nvim-neotest/neotest-python#48]
Hi! 👋 

I'm using LazyVim and it comes with a [pre-configured command](https://www.lazyvim.org/plugins/extras/test.core#neotest-1) (click "full spec") for running all tests:

```lua
{ "<leader>tT", function() require("neotest").run.run(vim.loop.cwd()) end, desc = "Run All Test Files" },
```

However, this command does nothing for me.

I've got my neotest-python adapter set up like this (full config [here](https://github.com/fredrikaverpil/dotfiles/blob/main/nvim-lazyvim/lua/plugins/test.lua#L33)):

```lua
adapters = {
  require("neotest-python")({
    runner = "pytest",
    args = { "--log-level", "INFO", "--color", "yes", "-vv", "-s" },
  }),
```

Am I doing something wrong here?

## More info:
- I can run individual tests just fine using e.g. `require("neotest").run.run()`.
- I originally opened up a discussion here about it in https://github.com/LazyVim/LazyVim/discussions/901 and an issue  in https://github.com/LazyVim/LazyVim/issues/931 but in both cases I was pointed here.
- I can run all tests with `require("neotest").run.run({ suite = true })` althought it makes neovim really slow for quite some time, even after all tests have executed.

## Steps to reproduce:
1. Launch neovim from the python project root dir with virtualenv activated. Open a test file.
2. Run the `require("neotest").run.run(vim.loop.cwd())` command via LazyVim's preconfigured `<leader>tT`.
3. Observe how no tests are running in the test summary tree, or in the output panel.

**Comment by catanzaromj** [comment]
Here's what works for me (I got these from the neotest docs):

To run all tests in the current file:
```python
function()
        require("neotest").run.run(vim.fn.expand("%"))
      end,
```

To run all tests in the current project:
```python
      function()
        require("neotest").run.run(vim.fn.getcwd())
      end,
```
Can you try these and see if they work?

**Comment by fredrikaverpil** [comment]
@catanzaromj yes, they both work for me.

I also think something was wrong with my setup, because now the `require("neotest").run.run(vim.loop.cwd())` command works too... 🤷 😆 

I'll close this issue.
