### ISSUE TITLE
How to send args to 1 command?

### ISSUE THREAD

**Issue by mrparalon** [nvim-neotest/neotest-python#56]
For example, I run `:lua require"neotest".run.run()` and for a single test I want to send `--pdb` args.

But I don't need it for whole file.

**Comment by rcarriga** [comment]
You can't specify arguments for just one test if you are running all tests in a file, pytest has no functionality for that

**Comment by mrparalon** [comment]
I'm not sure, that I get your answer right.

I can do `pytest --pdb tests/test_hooks.py::test_readiness_probe` and it works as expected
