### ISSUE TITLE
Tests not found with newest commits

### ISSUE THREAD

**Issue by tbung** [nvim-neotest/neotest-python#6]
When I try to run a test pytest cannot find it. Pytest itself does work. I assume this is an error with the test path given to pytest. I am not sure if this should be an issue with neotest or neotest-python, since I can only test on python currently I opened it here.

```
================================================= test session starts ==================================================
platform darwin -- Python 3.10.4, pytest-7.1.2, pluggy-1.0.0
rootdir: /Users/tillb/Projects/debugging, configfile: setup.cfg
collected 0 items                                                                                                      

================================================ no tests ran in 0.00s =================================================
ERROR: file or directory not found: test_debugging.py::test_fib
```

Code to reproduce:
```python
import pytest

def fib(n: int) -> int:
    if n < 2:
        return n
    else:
        return fib(n - 1) + fib(n - 2)


@pytest.mark.parametrize(
    ("input", "expected"), [(0, 0), (1, 1), (2, 1), (3, 2), (4, 3), (5, 5), (10, 55)]
)
def test_fib(input: int, expected: int):
    assert fib(input) == expected
```

Config:
```lua
require("neotest").setup({
  output = {
    enabled = true,
    open_on_run = "yes",
  },
  adapters = {
    require("neotest-python")({
      runner = "pytest",
      dap = { justMyCode = false, console = "integratedTerminal" },
    }),
  },
})
```

**Comment by rcarriga** [comment]
Can you provide the log file in `stdpath("log")` called `neotest.log`. There will be info on projects such as file structure so you can remove and rerun with a non-sensitive repo if that is a concern

**Comment by rcarriga** [comment]
Actually please try with latest neotest master, fixed a regression in the position tracking

**Comment by tbung** [comment]
That works, thanks for the quick fix!

I hope I'm not to spammy with my issues, I really like this plugin and am using it extensively already!

**Comment by rcarriga** [comment]
Glad to hear it works! No problem at all with issues, delighted to have them found quickly :grin:
