### ISSUE TITLE
Options or command line for test runner

### ISSUE THREAD

**Issue by wookayin** [nvim-neotest/neotest-python#7]
My project is based on `pytest`, and I would like to use some custom options or command line flags for the pytest runner. 

One particular example would be `pytest --verbose --capture=no`, so that I can see the standard output printed and captured during the test in the output view. I think this should be configurable via lua config or *dynamically* via run API (sometimes I would want to use just `pytest` or sometimes `pytest -v`, etc.). This feature would be not necessarily only for python but for all other languages/adapters in general.

**Comment by wookayin** [comment]
My desired pytest cmdline argument is `pytest -vv -s`. With the following config

```lua
adapters = {
  require("neotest-python")({
    dap = { justMyCode = false },
    args = { "-vv -s" },
    --runner = 'pytest',
  }),
  require("neotest-plenary"),
},
```

the output I get is:
```
ERROR: usage: neotest.py [options] [file_or_dir] [file_or_dir] [...]      
neotest.py: error: argument -v/--verbose: ignored explicit argument ' -s' 
```

When I try instead the following
```
    args = { "-s" },
```
the `-s` option seems to be applied on the pytest runner as expected. So maybe the above was just a corner case about dealing with the `-v/--verbose` option.

**Comment by rcarriga** [comment]
You need to separate the arguments `args = { "-vv", "-s" },`.

> dynamically via run API

You can already do that with `extra_args` option

**Comment by wookayin** [comment]
```
args = { "-vv", "-s" }
```
Thanks, this works. Appreciate answering a dumb question!
