### ISSUE TITLE
No tests found if another adapter is registered as well

### ISSUE THREAD

**Issue by HiPhish** [nvim-neotest/neotest-python#75]
My configuration is as follows:

```lua
local adapters = {
	require 'neotest-python' {
		runner = 'pytest',
		dap = {
			justMyCode = false
		},
	},
	require 'neotest-busted',
}
```

As you can see there are two adapter registered: neotest-python and [neotest-busted](https://github.com/hiphish/neotest-busted). However, as long as neotest-busted is in the list no Python tests are found. Once I remove it everything works fine. The `is_test_file` function from the Python adapter is never called, only the one from the busted adapter.

Maybe I am misunderstanding how adapters get chose, but my expectation would have been that Neotest tries the `is_test_file` functions from all adapters until one succeeds. Is there something about neotest-busted that makes it clobber neotest-python?

**Comment by MijikHna** [comment]
I am facing the same issue. @HiPhish have you found a solution?

**Comment by HiPhish** [comment]
@MijikHna No, but I have not been looking into it either.

**Comment by ramboman** [comment]
I had the same problem when I tried to register `neotest-bash` along side with `neotest-python`. I posted an issue regarding this problem at [rcasia/neotest-bash#17](https://github.com/rcasia/neotest-bash/issues/17). @rcasia's [response](https://github.com/rcasia/neotest-bash/issues/17#issuecomment-2183972514) explains properly what is going on. @rcarriga's [response](https://github.com/nvim-neotest/neotest-python/issues/40#issuecomment-1336947205) for another [issue](https://github.com/nvim-neotest/neotest-python/issues/40) offers a solution to the problem.

**Comment by MijikHna** [comment]
@ramboman Thank you for your hint. I have just created a python project file (in my case `pyproject.toml`) and tests has been discovered.

**Comment by HiPhish** [comment]
@ramboman Thanks, that helped.  I have taken out the fallback to the current working directory from my adapter, now everything works fine.  I'm closing this issue.
